# Generated by Django 5.1.3 on 2024-11-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_type_delete_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedán'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupé'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Truck', 'Camioneta'), ('Van', 'Furgoneta'), ('Minivan', 'Miniván'), ('Motorcycle', 'Motocicleta'), ('Electric', 'Eléctrico'), ('Hybrid', 'Híbrido'), ('Luxury', 'De lujo'), ('Sports', 'Deportivo'), ('Pickup', 'Pickup')], max_length=20, null=True),
        ),
    ]
