# Generated by Django 5.1.3 on 2024-11-13 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available_from',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
