# Generated by Django 5.1.3 on 2024-12-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available',
            field=models.BooleanField(choices=[('Si', 'No')]),
        ),
    ]
