# Generated by Django 5.1.3 on 2024-12-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available',
            field=models.BooleanField(choices=[('No', 'No'), ('Yes', 'Si')]),
        ),
    ]
