# Generated by Django 5.1.3 on 2024-12-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.BooleanField(choices=[('Iquique', 'Iquique'), ('Valparaíso', 'Valparaíso'), ('Santiago', 'Santiago')]),
        ),
    ]
