# Generated by Django 5.1.3 on 2024-12-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicle_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasolina'), ('Diesel', 'Diesel'), ('Electric', 'Electrico'), ('Hybrid', 'Hibrido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatico'), ('Manual', 'Manual')], max_length=20),
        ),
    ]
