# Generated by Django 5.1.3 on 2024-12-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_vehicle_fuel_type_alter_vehicle_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available',
            field=models.BooleanField(choices=[('No', 'No'), ('Si', 'Si')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.BooleanField(choices=[('', 'Iquique'), ('', 'Valparaíso'), ('', 'Santiago')]),
        ),
    ]
