# Generated by Django 5.1.3 on 2024-12-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_vehicle_available_alter_vehicle_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], max_length=20),
        ),
    ]
