# Generated by Django 5.1.3 on 2024-12-09 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_vehicle_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta'),
        ),
    ]
