# Generated by Django 5.1.3 on 2024-12-09 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_alter_vehicle_daily_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='available',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='daily_rate',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de venta'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sale_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido')], default='AVAILABLE', max_length=20, verbose_name='Estado de venta'),
        ),
    ]
